#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.7 (standalone edition) on Mon Jun 03 18:08:26 2013
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PrincipalFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PrincipalFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Simulacion: Remisera"))
        self.label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Introduzca los valores para la simulacion:"))
        self.label_2_copy = wx.StaticText(self.panel_1, wx.ID_ANY, _("Cantidad de remises:"))
        self.cantidad_remises = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "", min=0, max=100)
        self.label_2_copy_copy = wx.StaticText(self.panel_1, wx.ID_ANY, _("Tiempo de simulacion (dias):"))
        self.tiempo_simulacion = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.label_2_copy_1 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Resultados:"))
        self.label_2_copy_copy_1 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Pasajeros Perdidos:"))
        self.pasajeros_perdidos = wx.StaticText(self.panel_1, wx.ID_ANY, _("0"))
        self.label_2_copy_copy_1_copy = wx.StaticText(self.panel_1, wx.ID_ANY, _("Porcentaje de pasajeros perdidos:"))
        self.pasajeros_perdidos_porc = wx.StaticText(self.panel_1, wx.ID_ANY, _("0"))
        self.label_2_copy_copy_1_copy_copy = wx.StaticText(self.panel_1, wx.ID_ANY, _("Tiempo de espera Promedio:"))
        self.tiempo_espera = wx.StaticText(self.panel_1, wx.ID_ANY, _("0"))
        self.label_2_copy_copy_1_copy_copy_copy = wx.StaticText(self.panel_1, wx.ID_ANY, _("Tiempo Ocioso Promedio:"))
        self.tiempo_ocioso = wx.StaticText(self.panel_1, wx.ID_ANY, _("0"))
        self.simular = wx.Button(self.panel_1, wx.ID_ANY, _("Simular!"))
        self.ver_graficos = wx.Button(self.panel_1, wx.ID_ANY, _("Ver Graficos..."))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PrincipalFrame.__set_properties
        self.SetTitle(_("Simulacion Remiseria"))
        self.label_1.SetFont(wx.Font(20, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.label_2.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Calibri"))
        self.label_2_copy.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.cantidad_remises.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_2_copy_copy.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.tiempo_simulacion.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.label_2_copy_1.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Calibri"))
        self.label_2_copy_copy_1.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.pasajeros_perdidos.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.label_2_copy_copy_1_copy.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.pasajeros_perdidos_porc.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.label_2_copy_copy_1_copy_copy.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.tiempo_espera.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.label_2_copy_copy_1_copy_copy_copy.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.tiempo_ocioso.SetFont(wx.Font(15, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, "Calibri"))
        self.panel_1.SetMinSize((430, 479))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PrincipalFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.label_2, 0, wx.LEFT | wx.TOP, 10)
        sizer_3.Add(self.label_2_copy, 0, wx.LEFT | wx.TOP, 10)
        sizer_3.Add(self.cantidad_remises, 0, wx.LEFT | wx.TOP, 10)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.label_2_copy_copy, 0, wx.LEFT | wx.TOP, 10)
        sizer_4.Add(self.tiempo_simulacion, 0, wx.LEFT | wx.TOP, 10)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add(self.label_2_copy_1, 0, wx.LEFT | wx.TOP, 10)
        sizer_5.Add(self.label_2_copy_copy_1, 0, wx.LEFT | wx.TOP, 10)
        sizer_5.Add(self.pasajeros_perdidos, 0, wx.LEFT | wx.TOP, 10)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_6.Add(self.label_2_copy_copy_1_copy, 0, wx.LEFT | wx.TOP, 10)
        sizer_6.Add(self.pasajeros_perdidos_porc, 0, wx.LEFT | wx.TOP, 10)
        sizer_2.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_7.Add(self.label_2_copy_copy_1_copy_copy, 0, wx.LEFT | wx.TOP, 10)
        sizer_7.Add(self.tiempo_espera, 0, wx.LEFT | wx.TOP, 10)
        sizer_2.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_8.Add(self.label_2_copy_copy_1_copy_copy_copy, 0, wx.LEFT | wx.TOP, 10)
        sizer_8.Add(self.tiempo_ocioso, 0, wx.LEFT | wx.TOP, 10)
        sizer_2.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_9.Add(self.simular, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_9.Add(self.ver_graficos, 0, wx.ALL | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_2.Add(sizer_9, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class PrincipalFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Principal = PrincipalFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(Principal)
    Principal.Show()
    app.MainLoop()